# Generated by Django 3.0.3 on 2020-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='order',
            field=models.CharField(default='p', max_length=150),
            preserve_default=False,
        ),
    ]
