# Generated by Django 3.0.3 on 2020-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foca', '0002_auto_20200224_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='tamt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='order',
            field=models.CharField(max_length=500),
        ),
    ]
