# Generated by Django 3.0.3 on 2020-02-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foca', '0003_auto_20200224_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='order',
            field=models.TextField(max_length=500),
        ),
    ]
